### ISSUE TITLE
sitemap file is not generated!

### ISSUE THREAD

**Issue by idesignzone** [jbaubree/vite-plugin-pages-sitemap#1]
Hello. Thank you for the plugin. It was definitely necessary to have a sitemap solution that works with vue 3 and vite.
I setup as instructed but still cant see any sitemap file generated in the public folder of the project.
It also would be nice if you can give an example on how to use the options for example to change the default "hostname".

**Comment by jbaubree** [comment]
Hi, i share you an example with @antfu Vitesse project.

```
git clone git@github.com:antfu/vitesse.git
cd vitesse
pnpm i
pnpm i -D vite-plugin-pages-sitemap // (v1.0.1 will be installed)
```

Now edit the vite.config.ts
transform this
```
// https://github.com/hannoeru/vite-plugin-pages
Pages({
  extensions: ['vue', 'md'],
}),
```

to this
```
// https://github.com/hannoeru/vite-plugin-pages
Pages({
  extensions: ['vue', 'md'],
  onRoutesGenerated: routes => generateRoutes({
    hostname: 'https://mywebsite.com/',
    dest: 'public',
    filename: 'sitemap.xml',
    routes,
  }),
}),
```

Now you can run `pnpm dev`
and you will get sitemap.xml in public folder with hostname 'https://mywebsite.com/' :)

**Comment by idesignzone** [comment]
@jbaubree I still cant generate a sitemap with this setup.


import generateRoutes from 'vite-plugin-pages-sitemap'
import type { RouteRecordRaw } from 'vue-router'

export default defineConfig({
  resolve: {
    alias: {
      "~/": `${path.resolve(__dirname, "src")}/`,
    },
  },
  plugins: [
    vue(),
    Pages({
      onRoutesGenerated: routes => generateRoutes({
        hostname: 'https://mywebsite.com/',
        dest: 'public',
        filename: 'sitemap.xml',
        routes,
      })
    })
  ]
})

It seems like the instruction in the repo is somehow different from the example you provided here.

**Comment by jbaubree** [comment]
Mmh well,
Can you provide a repo with reproduction of not fonctionnal generator?

**Comment by idesignzone** [comment]
My project is similar to [this repo](https://github.com/web2033/vite-vue3-tailwind-starter)

**Comment by jbaubree** [comment]
From this project, you have some things to change:
`npm install -D vite-plugin-pages`
`npm install -D vite-plugin-pages-sitemap`

in main.js :
```
// import { routes } from './routes.js'
import routes from "~pages"
```

in vite.config.js :
```
  plugins: [
    vue(),
    Pages({
      dirs: 'src/views',
      onRoutesGenerated: routes => (generateSitemap({ routes })),
    }),
  ],
```

I hope this will be helpfull

**Comment by jbaubree** [comment]
@idesignzone Did you fixed your issue? If you have more trouble, we can take few minutes to check this together

**Comment by idesignzone** [comment]
@jbaubree I was able to generate the sitemap after your instruction. 
Thank you very much for the help. really appreciate it. 
my setup for vite.config.ts

```
import generateRoutes from 'vite-plugin-pages-sitemap'

export default defineConfig({
  resolve: {
    alias: {
      "~/": `${path.resolve(__dirname, "src")}/`,
    },
  },
  plugins: [
    vue(),
    Pages({
      onRoutesGenerated: routes => generateRoutes({
        hostname: 'https://mywebsite.com/',
        dest: 'public',
        filename: 'sitemap.xml',
        routes,
      })
    })
  ]
})
```
