### ISSUE TITLE
Generate sitemap only during build proccess

### ISSUE THREAD

**Issue by tadeucaldas** [jbaubree/vite-plugin-pages-sitemap#113]
Is it possible for me to generate the sitemap xml file during build only? i searched the 'changefreq' option in the repository and could see if it is possible or not.

**Comment by tadeucaldas** [comment]
i think i made a stupied question.. didn´t know  much about sitemap xml before asking.. sorry! it is denifed on http://www.sitemaps.org/schemas/sitemap/0.9 xsd right?

**Comment by jbaubree** [comment]
Hi, if you want to generate sitemap on build, try https://github.com/jbaubree/vite-ssg-sitemap or https://www.npmjs.com/package/vite-plugin-sitemap if you dont use vite-ssg.
