### ISSUE TITLE
Sitemap not generating

### ISSUE THREAD

**Issue by TheHunterDog** [jbaubree/vite-plugin-pages-sitemap#131]
After updating my dependency's, the sitemap doesn't generate anymore. After this experience I tested the example in your GitHub to test if something was wrong with my config. Unfortunately it wasn't the case the example also doesn't work.

**Comment by jbaubree** [comment]
Can you provide me a repo with your issue ? The example si working, if you clone project, your run dev and example:dev, you will see sitemap.xml and robot.txt in example/public.

**Comment by TheHunterDog** [comment]
> Can you provide me a repo with your issue ? The example si working, if you clone project, your run dev and example:dev, you will see sitemap.xml and robot.txt in example/public.

The sitemap is not generating in the example folder. I am running npm run dev like you said.

**Comment by jbaubree** [comment]
you need to run pnpm dev and pnpm example:dev in another terminal. Next, open your localhost to generate sitemap.

**Comment by TheHunterDog** [comment]
was working on a older version of vite and a newer version of sitemap. The sitemap wasn't generating in the example for me because I wasn't visiting the local url.
