### ISSUE TITLE
Sitemap generates and works locally. But doesn't work when deployed on firebase.

### ISSUE THREAD

**Issue by techniath** [jbaubree/vite-plugin-pages-sitemap#170]
I am facing weird issue where I am able to generate the sitemap and run it locally using localhost:3000/sitemap.xml. I updated the hostname as shown below and when I run it locally I can see the sitemap with my domain name. But after deploying it to firebase the response is blank. Am I missing something? Please guide

onRoutesGenerated: (routes) =>
      generateSitemap({
        hostname: 'https://mydomainname.web.app/',
        dest: 'public',
        filename: 'sitemap.xml',
        routes,
      }),
  }),

**Comment by jbaubree** [comment]
is sitemap.xml generated in your dist folder next build ?

**Comment by techniath** [comment]
> @techniath is sitemap.xml generated in your dist folder next build ?

Yes, its generated.

**Comment by jbaubree** [comment]
<img width="1439" alt="Capture d’écran 2022-10-18 à 23 42 07" src="https://user-images.githubusercontent.com/50230578/196550300-5fa59f3e-515a-490c-a6cd-d2d7fc41f697.png">

I think you have cache issue...

**Comment by techniath** [comment]
> <img alt="Capture d’écran 2022-10-18 à 23 42 07" width="1439" src="https://user-images.githubusercontent.com/50230578/196550300-5fa59f3e-515a-490c-a6cd-d2d7fc41f697.png">
> 
> I think you have cache issue...

Ohh, lol. Thank you so much. I spent 3 days trying to fix this. Now feel dumb but happy that it's finally solved. 

Thank again
