### ISSUE TITLE
generateSitemap is not a function [Error]

### ISSUE THREAD

**Issue by LittleWhiteLoti** [jbaubree/vite-plugin-pages-sitemap#173]
Can you tell me what I'm doing wrong? I followed the example in the docs

![image](https://user-images.githubusercontent.com/61956115/197244136-294a3ef1-2327-4e79-9b66-a6d52179978d.png)

![image](https://user-images.githubusercontent.com/61956115/197243928-6c1a7655-80d0-4bc0-b74e-d4df20a03928.png)

![image](https://user-images.githubusercontent.com/61956115/197243864-ef78ea38-b36d-4c29-963a-f8f9c4283c26.png)

**Comment by jbaubree** [comment]
I think you have to call generateSitemap.default(). I will create a new build with auto importing as default for next version. Thanks for reporting and fill free to close this issue if it's ok for you.

**Comment by LittleWhiteLoti** [comment]
Noted, thanks for the reply

**Comment by jbaubree** [comment]
@LittleWhiteLoti I have just made library update. You can now upgrade to `v1.4.5` and you will be able to use generateSitemap() without default function.

**Comment by LittleWhiteLoti** [comment]
Thanks for looking into that! I will bring it into my code.
