### ISSUE TITLE
Missing hostname slash in routes

### ISSUE THREAD

**Issue by sumberacstefano** [jbaubree/vite-plugin-pages-sitemap#241]
When you build the app sitemap.xml contains hostname `<loc>http://localhost/</loc>` with a slash on the end.
Every next `<loc>` looks like this `<loc>http://localhostterms-and-privacy</loc>` without the slash at the end of the hostname.

Workaround is to provide routes manually in vite.config.js `routes: ['/', '/terms-and-privacy']` which is ok as long as you don't have many routes.

**Comment by jbaubree** [comment]
@sumberacstefano i don't understand your issue, if you configure `http://localhost/` as hostname and you send routes generated by `vite-plugin-pages` it works as expected.
If there is another problem, can you share a repo with reproduction of your issue?
Thanks

**Comment by sumberacstefano** [comment]
@jbaubree Sorry, I guess something was setup badly inside my environment. Thanks!
