### ISSUE TITLE
Nested routes are not generated in sitemap

### ISSUE THREAD

**Issue by paramr** [jbaubree/vite-plugin-pages-sitemap#3]
Nested routes like examples given in: https://router.vuejs.org/guide/essentials/nested-routes.html do not work with sitemap. This is because https://github.com/jbaubree/vite-plugin-pages-sitemap/blob/e6d9f6efe7de0d3b40b61aa218fd4cf990fd32d8/src/index.ts#L29 only looks at top level routes (expecting flat list of routes).

To see sample code on how to recurse through the nested routes:
https://github.com/antfu/vite-ssg/blob/3adec80118d6f008fd2f6ffafcc08cb0101284ce/src/node/utils.ts#L13

Work around is to flatten the hierarchy and pass it to generateSitemap, but supporting it natively would be awesome.

**Comment by paramr** [comment]
Interestingly I could use your other project (https://github.com/jbaubree/vite-ssg-sitemap) which uses generated html from vite-ssg :)

**Comment by jbaubree** [comment]
Thanks for the report, you are right, this plugin didn't generate nested routes.
I have just fixed this on `v1.2.0`.

**Comment by jbaubree** [comment]
> Interestingly I could use your other project (https://github.com/jbaubree/vite-ssg-sitemap) which uses generated html from vite-ssg :)

If you are using vite-ssg, i will recommend to use `vite-ssg-sitemap` who works great :D
