### ISSUE TITLE
Should specify Prerequisites

### ISSUE THREAD

**Issue by kg-pb** [jbaubree/vite-plugin-pages-sitemap#351]
You should specify in your readme, that it only works if you use [vite-plugin-pages](https://github.com/hannoeru/vite-plugin-pages).
I spent several hours to figure out why it doesn't work, just to know that this is requirement. Not Cool!

**Comment by jbaubree** [comment]
Hi,
Thanks for your comment. I think vite-plugin-pages use is explicit. You can see `vite-plugin-pages based sitemap generator` in the first line of readme.
 [Configuration tutorial](https://github.com/jbaubree/vite-plugin-pages-sitemap#vite-config) explain that you need to use vite-plugin-pages:
```
npm install -D vite-plugin-pages
npm install -D vite-plugin-pages-sitemap
npm install vue-router@next
```

If you have more readable solution for that, feel free to make a PR
