### ISSUE TITLE
custom robot.txt

### ISSUE THREAD

**Issue by Cephaz** [jbaubree/vite-plugin-pages-sitemap#636]
# Feature Request: Add option to disable robots.txt generation or customize rules

## Description
Currently, the plugin automatically generates a robots.txt file without the possibility to disable this generation or customize specific rules. This can be problematic when users need to:
- Use their own robots.txt file from the public directory
- Add specific disallow rules for certain files or directories
- Have more granular control over robots.txt content

## Proposed Solution
Add one or both of these options to the plugin configuration:
```
generateRobotsTxt: bool,
or
robotsRules: [{
   userAgent: string;
  allow?: string[];
  disallow?: string[];
}, ...]
```

**Comment by jbaubree** [comment]
Hi @Cephaz 
Thank you for your interest, if you need this feature, you can develop it and open a pull request. You can find some examples  [here](https://github.com/jbaubree/sitemap-ts) to help you.
